version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/lucassabreu/clockify-cli"
  dependencies_vendored = false

[[analyzers]]
name = "test-coverage"
enabled = true
